name: Fetch JSON and Create PR
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch JSON Data
        id: fetch-json
        uses: engahmeds3ed/create-json-url@v0.0.1
        with:
          name: 'data.json'
          url: 'https://s3.ap-south-1.amazonaws.com/qa.unifyapps.com.cloudstorage.1/1/workflow_uploads/local_file/a7fdd0f3-493c-4c7b-a69c-2e5fd522c75e241db3e8-2209-4e4e-ad28-205a3aa561f8?response-content-disposition=attachment%3Bfilename%3D%22a7fdd0f3-493c-4c7b-a69c-2e5fd522c75e241db3e8-2209-4e4e-ad28-205a3aa561f8%22&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEAptCR%2Fywim9T%2F5X2fyjBtajidYLGu6lVudf69SfRA3HgCIGVkLSSXgJsy9eJDT%2F73xr1hLEhpfUFmjeGpIa3OvPteKscFCKT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNTQ2OTE4MTA2MjgzIgzVsjHAtfopsJOI%2FgcqmwV79y1y2q%2BHzp%2FtJ0Jyn79U2C9JCCd1u3nMZbBtMb%2FJsdOzwC4%2BH0W8EuPjTobLAaHsKKcDTlyHdcdp39mbv2VlSmJFEVWrQbFKMgoZirlVIAuQT%2FXMueoGmzWClXTLhS6g2FqKvOyfPHo%2FnOMx3gOfT6sGs1VeGlwtRs33vwj6oJL%2B%2Fh49ly9AvJeIWMTJx3cDaZvqvTc13tkxMhQU%2BivuKz8htDddLsKWgdp%2Fh7Al5uXrdxSEuUMUulLCTHjDPrVYiYbJJp1%2BN9Hl55hCRB7K8Kj9iGI29V1nC6TsXRpIkXlYhg7DBHqpjYpRKJph2clPo4Ud2BgLm4cgWEC%2FhcSTYmNwBM%2BzUc5MM0PepZgm5gCwXWo893BZljaxYWzmkPKxLi8WI%2BSjEnmMwNkxDUCsdCO2xkWtvf1ngPVdstQOTG0twKSHZqETKt%2BKYNG4%2F0fklQD%2Fyj0rQRgzWbLzPHn%2FQo3Fho8kT%2B%2B5nHXNgHWtoeRZUVloVkbvrfA%2BMvkD6ACN2LQmexP6usrN9f2mwIEp9S2zrLOe1Z7sJ6EYBUU378Z8f05lx%2BEZstZo1roR%2FI8cV7kTuHNfYk%2BG95aQYxqPl0bb4WMSsWa%2FIyRc1WXG1%2FwGWMio3y1vrmNcFMF1EE2jKto9I7slcqQt53sSjpwm6I%2BOJwPYKON%2FYzjKmD3Qm7mqY3GxJ46wP%2BPjbDOaheao5ux25JwknXt%2Fv0F0zoY%2FMO%2BV8YSOEACdAOHRyMlXRD0ZICYkAgJNzpN3rRujiTwc2kPoSdcSxhrQyzPnfo5ufxg%2BXC%2B3BUOXbOP3NAAeCRg2S62CWphcnQf%2FKPozH6Fa4olPdTtDjQpi3UF8rzGZ3G39vimyr0STQj%2Fy49R4gGCLG8ZbZJL3NnvjMIb6msIGOrEByMK9TvV4Xv6uKzIlb37YuttOnVVuepcrajEZeWdmltYDHPwVzEk5XxxVbhPseH9EK9teVxHkKEFUf%2Fa2sc65nZfKIrErG4IaMrkxttK5MroN04clMpSEFsK6s8TwsiFKb8izVcfQ0r%2Bm1sV5UWRvzrfDc2flATkgvPsOHDr5wfP2afKY7JvqQbUMnbVvmvGtKcYvdoYoebiDgbxyDZ1yOjTjqoZWr6qsodnq22%2BMH7MZ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250609T111938Z&X-Amz-SignedHeaders=host&X-Amz-Credential=ASIAX6VW4ASVRDBRFQQZ%2F20250609%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Expires=3600&X-Amz-Signature=f409ee9d1b3061d0b774047f3ea24fefd0b8ff6d92739526f10967f4952c45a1'
          dir: 'data'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update JSON data from GitHub Gist'
          title: 'Automated JSON Data Update'
          body: 'This PR updates the JSON data fetched from GitHub Gist.'
          branch: 'auto-update/json-data'
          base: 'main'
          delete-branch: true
