name: Fetch JSON and Create PR
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch JSON Data with curl
        run: |
          mkdir -p data
          curl --insecure -o data/data.json https://jsonkeeper.com/b/XP9J

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update JSON data from jsonkeeper.com'
          title: 'Automated JSON Data Update'
          body: 'This PR updates the JSON data fetched from https://jsonkeeper.com/b/XP9J.'
          branch: 'auto-update/json-data'
          base: 'main'
          labels: 'automated, data-update'
          delete-branch: true
