name: Fetch JSON and Create PR
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch JSON Data
        id: fetch-json
        uses: engahmeds3ed/create-json-url@v0.0.1
        with:
          name: 'data.json'
          url: 'https://s3.ap-south-1.amazonaws.com/qa.unifyapps.com.cloudstorage.1/1/workflow_uploads/local_file/49cfabdc-08af-441a-9a80-c4b967979195d682e034-3f0d-4106-8398-2b8071c03988?response-content-disposition=attachment%3Bfilename%3D%2249cfabdc-08af-441a-9a80-c4b967979195d682e034-3f0d-4106-8398-2b8071c03988%22&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEM7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEA1FT7dIB6AfLazqnkjwTaeatbvEm%2FLs1QLYqW8FNhVyQCICGJIPKNrni6lDEG%2FkGlvgDJHFQCwA09VULYojPzEJtyKsgFCKf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNTQ2OTE4MTA2MjgzIgx7ePUL%2BhfqRNJ1998qnAV%2ByTU0v6JmycHAQqivK4IxDY3tJ8PFlu78BYyFy51250Tzu3CIpctfqfWa8Lwua9L4IxuhkMsbHP2VQckDWSFth2UkaIui4iTgK9ol5XmA4dSZK%2FovFopK1GNlGJoBLFaIEbp9G5Tm038hW8SBPFbKInw%2B3bPSzA%2BFJZJUeUvvYDTdjh%2FXSqYxfBDFES2f81oRmVT1POf%2B4jyObwtKiqNZJWn94S25X%2FwZjy5d8qgy6jvqNANjYb%2Fr6Bpgwe%2BfbOz7QZOuzos4wA%2BODgJaT7FZKo636S5oeuanWT6Phn%2BxNb0GyFPG%2Ba%2FUxzSxZjefNeGuJPZKtZ%2Bhs%2BUPIhqKLuT82pLQSAKPO%2FLlrthtnozhWfbCY1Y91ouOncnferROQGRqgvo%2FwGecwnQexg81hw6nlokMyI6HJPXRQTUabsrv0xnmUlWuXNuOn56u82fR%2FGMEPrBH97kQEEUAtauE2JNxlUGtPKsfFu%2FUsFjoqeg9c0sOk3BeUDoYVvLlGK7BfQkyqtVQIWadEQA%2FlXl1SY7Wpg6WGOaneXau%2BySNL2adxOTZWq%2F89OV4VawdZgW9FbVesPM4Yj23v59puef6a0jIJRVluJq3P1%2Bw6O%2BQbm%2FPVWr0TZb6Jp6SzmFwXcIMyjBrZWgtKOEJRbvd6l7xstPQVl9fvD5js5Gqr3dlqgPlJoD1ER%2FBqOFqCByATP1UoHeV0vzxuS%2BJCCmtg%2Ba6wLoTOfBzcyW5KbTk7dO3pWv2heimTTFcypouYNk8grDhN71FfRLoaPZ5lzeHqigaoyZBoCkceNmT84d1lM%2F8qbpFsrHTbP42FKWaun%2B2Orcugbf7sD85JRNpLOyfNbGQ4G6njyn8BUfAWZ9JywfMOrZLchmo%2BUiInqTLDSCepjCyz5vCBjqxAQUHC7a1Siu%2FVTNnmcFf2tMzKFdYdLjPK6mfwIH%2FjpVxiNlLi0UtYJhtw5JgSAiA8fprU7i8oolxUjWwdIc1c0wcQ%2BH4d7ufUeohX5R9AJEfYyFktxSXb%2BhQBLmIZQ9pLYPBGK2jy3n%2Bfg4kGqCSkdv4nGggMp0Adltcvw4HHGUV1x3WFFXIWMrL6c%2Fy1VNOyWD2UB9Ss%2F2ImckUlIk9qGvxcjfYUzXPYYz0zYccOrViiA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250609T142919Z&X-Amz-SignedHeaders=host&X-Amz-Credential=ASIAX6VW4ASVZJHHIFVV%2F20250609%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Expires=3600&X-Amz-Signature=0fac918a2d0e2cdf73e31e6f22030c37983d054fd12b6db55431e74f61b8fc02'
          dir: 'data'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update JSON data from GitHub Gist'
          title: 'Automated JSON Data Update'
          body: 'This PR updates the JSON data fetched from GitHub Gist.'
          branch: 'auto-update/json-data'
          base: 'main'
          delete-branch: true
