name: Fetch JSON and Create PR
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch JSON Data
        id: fetch-json
        uses: engahmeds3ed/create-json-url@v0.0.1
        with:
          name: 'data.json'
          url: 'https://s3.ap-south-1.amazonaws.com/qa.unifyapps.com.cloudstorage.1/1/workflow_uploads/local_file/2e354bfc-1d19-4b5e-8b78-c9d18ff4f02b25b494ec-71f1-4ea6-bc4b-24a71046aead?response-content-disposition=attachment%3Bfilename%3D%222e354bfc-1d19-4b5e-8b78-c9d18ff4f02b25b494ec-71f1-4ea6-bc4b-24a71046aead%22&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEA7urfTpiBirMI6uweD7ZbCuXcqXjuLn7ekjytoIUkouECIB8%2BmwGv08YYG8LWlD4Kj7kkyy1JBBk4GXCj5Ef8gHSaKsgFCKX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNTQ2OTE4MTA2MjgzIgz2qjT3rtLLYF%2BTLwYqnAVTdAIyeX%2BneSonXdII0bWHi6td0eF87B426CJ%2B2bTk6HFICmXIlwQEhYLemIzfkr%2FCuXFXeyb3njkpmBhW11BNVDm7JlnA6AoXYZ%2BDAYmZbP0te3tyohcSPsgSjOakVIhmUq%2BLW4i7uTMWdQnzh2yuUAyD7P%2F1H%2FF81Ky6CJtZ0K7tXDU%2BaryYFi%2FUi1Tkbw5vzKRYPOMZK247hUD8zAwJftFU4S7XxmBmjoI%2F%2BfyLtU5hpUUn4j2xnb00RZdzhpwiTWLKXB%2BxnV5deXCIqgWo2NTixGeCiCDRBVoFLZHDd4e%2FaJib%2B0KWKTBcr2yJ2Q0YiACRrxsqH5V0nOYeCYyP%2FQ8YRQ3LP5JZcNrxPNczzTmlJkQmWN51fSJHiEQOiqpCmJcN60dEbYi4WMfYcrnA4GNEDxl07hwpdt2o7%2FM0DfHNgX7VTonJGaroUxhvaUCrUQvrSIVpt5WyTEG6I5YJJ39Jv7FYaIyykFUWuDNE3U8x6QU3m%2BRK6Mgd5kOkXf3N7yor58hdtj3%2FrBjrEZGeUldaEPVA6RxrPapD9vzVN6oeQqvDsRuA7WqpWJzlUaxVf1k%2FxkdzoUKAsr%2FxZunsForeIJWoMb3ugYH2%2BKwq8kf6vShz%2BTee5ZqGKtvrsCOlE0RHsnaQcNVMQAFbkYNojq5J7N4xwjar93%2BlKJwPZjr10dneAoUWFbyF3CwD2bNhpn%2FzSdReVDFF4wBjfOLq10vhTF77Kn%2Bqu95OV5tYWBvMj69RC4USHSkgX42b95ycXNZXJHxH6fz8DvBarF6StMmBTx7siClCKIgX6Y9UnBALBV95t3MhR9XJ9Len5gfPKYxUzMxTMbi5HRKfLeormJejmfAzvNTmSP49pMRdE52aeWHRoumWW37sMDDikZvCBjqxAd6uFq%2FQTx7Mq3kEfoRkihRVRqZ8diyhcJxfxCKh9C4kyLVkeFdZ0cBBnAU8GG3MmVMxw8PwLkLt66yt4PLARwJatFUNoanIfaaaWIK0rqlbOgOyEf2c89XHBK%2FMJAXXIfmfbgJ8OqzOYLSYO%2FtjX%2BWiWJaY2OfQvZsaPZiebrjSH4q44uVw98Mq6dEjU7qGJ8ubrwwH3zqJjgmJ%2Fm8YppSgfGRUrRQj%2BaKZnC0yKNEJ3w%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250609T114450Z&X-Amz-SignedHeaders=host&X-Amz-Credential=ASIAX6VW4ASVUOIL5OZ2%2F20250609%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Expires=3600&X-Amz-Signature=de508bd7fb44f7595d822bbf82e5b528b5ec6e829d4054f6e114870a93571328'
          dir: 'data'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update JSON data from GitHub Gist'
          title: 'Automated JSON Data Update'
          body: 'This PR updates the JSON data fetched from GitHub Gist.'
          branch: 'auto-update/json-data'
          base: 'main'
          delete-branch: true
