name: Fetch JSON and Create PR

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Public URL of JSON file'
        required: true
        type: string
      name:
        description: 'Filename without extension (e.g., ua-platform)'
        required: true
        type: string

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JSON from URL
        run: |
          mkdir -p configs/entity/objects/interfaces
          curl -s "${{ github.event.inputs.url }}" -o "configs/entity/objects/interfaces/${{ github.event.inputs.name }}.json"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update: configs/entity/objects/interfaces/${{ github.event.inputs.name }}.json"
          title: "Automated Update: ${{ github.event.inputs.name }}.json"
          body: "This PR updates: configs/entity/objects/interfaces/${{ github.event.inputs.name }}.json"
          branch: "auto-update/json-${{ github.run_id }}"
          base: "main"
          delete-branch: true
